fix: Build Heirloom with musl >1.2.3 and NetBSD curses in mind.
The first "hack", if we must call it this way, fixes date(1)
since time.h doesn't include prototypes for syscalls that
are needed. The error goes like this:

gmake[1]: Entering directory '/dsk/0v/usr/tmp/obj/copausrspc/heirloom-ng-250220/date'
clang -O0 -fomit-frame-pointer -D_GNU_SOURCE   -I../libcommon -c date.c
date.c:154:2: error: call to undeclared function 'gettimeofday'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  154 |         gettimeofday(&tv_tmp, NULL);
      |         ^
date.c:291:6: error: call to undeclared function 'adjtime'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  291 |         if (adjtime(&tv, 0) < 0) {
      |             ^
date.c:291:6: note: did you mean 'asctime'?
/llvmtools/include/time.h:61:7: note: 'asctime' declared here
   61 | char *asctime (const struct tm *);
      |       ^
2 errors generated.
gmake[1]: *** [Makefile:326: date.o] Error 1
gmake[1]: Leaving directory '/dsk/0v/usr/tmp/obj/copausrspc/heirloom-ng-250220/date'
gmake: *** [makefile:26: all] Error 2
gmake: Leaving directory '/dsk/0v/usr/tmp/obj/copausrspc/heirloom-ng-250220'

The next fix tells Heirloom's build system that we're using
termcap instead of curses, simply because NetBSD curses
implements tparm() following the specification down to the
letter (excerpt from term.h):

/* You should note that the spec allows stuffing a char * into a long
 * if the platform allows and the %pN is followed immediately by %l or %s */
char *		tparm(const char *, long, long, long, long, long,
		long, long, long, long);

A little bit below, we've got a note saying that we could
use a function called tiparm() (not to be confunded with
ti_parm()), that have variadic arguments like ncurses'
default tparm() (another excerpt from term.h):

/* Using tparm can be kunkly, so provide a variadic function
 * Numbers have to be passed as int */
/* This is not standard, but ncurses also provides this */
char *		tiparm(const char *, ...);
/* And a thread safe version */
char *		ti_tiparm(TERMINAL *, const char *, ...);

This slight disagreement on how the function is prototyped
per default resulted in this error when compiling ls(1) ---
and would also appear when building shl(1) and watch(1)
further:

cc -O0 -fomit-frame-pointer -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64L  -c ls.c
ls.c:869:49: error: too few arguments to function call, expected 10, have 2
  869 |                 char *cp = tparm(set_a_foreground, COLOR_BLACK);
      |                            ~~~~~                              ^
/llvmtools/include/term.h:1961:9: note: 'tparm' declared here
 1961 | char *          tparm(const char *, long, long, long, long, long,
      |                 ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1962 |                 long, long, long, long);
      |                 ~~~~~~~~~~~~~~~~~~~~~~
ls.c:990:5: error: call to undeclared function 'vidattr'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  990 |                                 vidattr(A_BOLD);
      |                                 ^
ls.c:995:11: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
  995 |                         printf(color);
      |                                ^~~~~
ls.c:995:11: note: treat the string as an argument to avoid this
  995 |                         printf(color);
      |                                ^
      |                                "%s",
ls.c:1057:4: error: call to undeclared function 'vidattr'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1057 |                         vidattr(A_NORMAL);
      |                         ^
ls.c:1062:10: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
 1062 |                 printf(fc_get(FC_NORMAL));
      |                        ^~~~~~~~~~~~~~~~~
ls.c:1062:10: note: treat the string as an argument to avoid this
 1062 |                 printf(fc_get(FC_NORMAL));
      |                        ^
      |                        "%s",
2 warnings and 3 errors generated.
gmake[1]: *** [Makefile:326: ls.o] Error 1
gmake[1]: Leaving directory '/dsk/0v/usr/tmp/obj/copausrspc/heirloom-ng-250220/ls'
gmake: *** [makefile:26: all] Error 2
gmake: Leaving directory '/dsk/0v/usr/tmp/obj/copausrspc/heirloom-ng-250220'

For this, we have two possible solutions: using termcap
instead of curses (which I frankly doubt will be possible
because of watch(1), which hasn't been written considering
termcap if I remember correctly), which is the solution
we've chosen for now, and using '-DTPARM_VARARGS', which
I hadn't knew about until this very moment.